# Generated by Django 3.2.25 on 2024-11-05 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.CharField(blank=True, default='https://picsum.photos/200', max_length=255),
            preserve_default=False,
        ),
    ]
